### ISSUE TITLE
Build fhog_utils.py in windows

### ISSUE THREAD

**Issue by alimirzaei** [uoip/KCFnb#2]
I want to build this file in windows but I am not successful. I test with both msvc and mingw32 compiler but I got this error:

`compilation terminated.                                                                                                 Traceback (most recent call last):                                                                                        File "fhog_utils.py", line 125, in <module>                                                                               cc.compile()                                                                                                          File "C:\Users\Ali\Anaconda2\lib\site-packages\numba\pycc\cc.py", line 212, in compile                                    objects += self._compile_mixins(build_dir)                                                                            File "C:\Users\Ali\Anaconda2\lib\site-packages\numba\pycc\cc.py", line 187, in _compile_mixins                            extra_cflags=extra_cflags)                                                                                            File "C:\Users\Ali\Anaconda2\lib\site-packages\numba\pycc\platform.py", line 79, in compile_objects                       extra_preargs=extra_cflags)                                                                                           File "C:\Users\Ali\Anaconda2\lib\site-packages\numpy\distutils\ccompiler.py", line 230, in CCompiler_compile              single_compile(o)                                                                                                     File "C:\Users\Ali\Anaconda2\lib\site-packages\numpy\distutils\ccompiler.py", line 194, in single_compile                 self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)                                                        File "C:\Users\Ali\Anaconda2\lib\distutils\cygwinccompiler.py", line 166, in _compile                                     raise CompileError, msg                                                                                             distutils.errors.CompileError: Command "gcc -mdll -O -Wall -DMS_WIN64 -DPYCC_MODULE_NAME=fhog_utils -DPYCC_USE_NRT=1 -IC:\Users\Ali\Anaconda2\include -IC:\Users\Ali\Anaconda2\PC -IC:\\Users\\Ali\\Anaconda2\\lib\\site-packages\\numpy\\core\\include -c C:\Users\Ali\Anaconda2\lib\site-packages\numba\pycc\modulemixin.c -o c:\users\ali\anaconda2\lib\site-packages\numba\pycc\modulemixin.o" failed with exit status 1   `

Can I build it on windows? How?

**Comment by alimirzaei** [comment]
I built it in linux successfully.

**Comment by kanishka-namdeo** [comment]
Same here, I get

Traceback (most recent call last):
  File "fhog_utils.py", line 10, in <module>
    cc = CC('fhog_utils')
  File "C:\ProgramData\Anaconda2\lib\site-packages\numba\pycc\cc.py", line 62, i
n __init__
    self._toolchain = Toolchain()
  File "C:\ProgramData\Anaconda2\lib\site-packages\numba\pycc\platform.py", line
 61, in __init__
    self._raise_external_compiler_error()
  File "C:\ProgramData\Anaconda2\lib\site-packages\numba\pycc\platform.py", line
 104, in _raise_external_compiler_error
    raise RuntimeError(msg)
RuntimeError: Attempted to compile AOT function without the compiler used by `nu
mpy.distutils` present. Cannot find suitable msvc.

I have the necessary compilers for python 2.7 installed. Please help.
