### ISSUE TITLE
fhog_utils not working on Windows!

### ISSUE THREAD

**Issue by kanishka-namdeo** [uoip/KCFnb#3]
I get the folowing error when i try to run:

```
Traceback (most recent call last):
File "fhog_utils.py", line 10, in 
cc = CC('fhog_utils')
File "C:\ProgramData\Anaconda2\lib\site-packages\numba\pycc\cc.py", line 62, i
n init
self._toolchain = Toolchain()
File "C:\ProgramData\Anaconda2\lib\site-packages\numba\pycc\platform.py", line
61, in init
self._raise_external_compiler_error()
File "C:\ProgramData\Anaconda2\lib\site-packages\numba\pycc\platform.py", line
104, in _raise_external_compiler_error
raise RuntimeError(msg)
RuntimeError: Attempted to compile AOT function without the compiler used by nu mpy.distutils present. Cannot find suitable msvc.
```

**Comment by IdoWSC** [comment]
Hi,
I have the same problem

**Comment by uoip** [comment]
I test the code under Windows10 (with anaconda), and encounter similar problam. It's may due to incompatibility between Numba and Windows (because it works fine on Ubuntu), I don't know how to solve it...

**Comment by tjusxh** [comment]
@kane111 @uoip I also encounter the similar problem. Please Do you resolve the question?

**Comment by kanishka-namdeo** [comment]
@tjusxh Not yet, I'm planning to use the C++ implementation for better speed later.

**Comment by 1374207430** [comment]
look my project  transform to py3.6 and in ubantu
it also can run fhog_utils in win10 but can not run run.py 
i still debug it ......
